export const DEFAULT_SCHEDULES = {
  full: [
    { time:"5:00 AM",  label:"Wake + hydrate + 3-line journal",               type:"ritual"  },
    { time:"5:30 AM",  label:"Review today's plan (5 min)",                   type:"plan"    },
    { time:"6:00 AM",  label:"🔥 DEEP WORK BLOCK 1 — Tier 1 skill (2.5 hrs)", type:"work"    },
    { time:"8:30 AM",  label:"Breakfast + short break",                       type:"break"   },
    { time:"9:00 AM",  label:"🔥 DEEP WORK BLOCK 2 — Tier 1/2 skill (2.5 hrs)",type:"work"  },
    { time:"11:30 AM", label:"Break + stretch",                               type:"break"   },
    { time:"12:00 PM", label:"🔥 DEEP WORK BLOCK 3 — Tier 2 skill (1.5 hrs)", type:"work"    },
    { time:"1:30 PM",  label:"Lunch + proper rest",                           type:"break"   },
    { time:"2:30 PM",  label:"🔥 DEEP WORK BLOCK 4 — Side skill / review",    type:"work"    },
    { time:"4:30 PM",  label:"Break",                                         type:"break"   },
    { time:"5:00 PM",  label:"📤 GitHub push + LinkedIn post (1 hr)",          type:"habit"   },
    { time:"6:00 PM",  label:"Exercise / walk outside (1 hr)",                type:"health"  },
    { time:"7:00 PM",  label:"Dinner",                                        type:"break"   },
    { time:"8:00 PM",  label:"Concept review / tutorials (1.5 hrs)",          type:"review"  },
    { time:"9:30 PM",  label:"Plan tomorrow + quick journal",                 type:"plan"    },
    { time:"10:00 PM", label:"Wind down — no screens",                        type:"wind"    },
    { time:"11:00 PM", label:"😴 Sleep",                                      type:"sleep"   },
  ],
  exhausted: [
    { time:"5:00 AM",  label:"Slow wake — no pressure",                       type:"ritual"  },
    { time:"6:30 AM",  label:"Watch course videos only (passive)",             type:"review"  },
    { time:"8:30 AM",  label:"Breakfast + rest",                              type:"break"   },
    { time:"9:30 AM",  label:"ONE concept review only — max 1.5 hrs",         type:"work"    },
    { time:"11:00 AM", label:"Nap if needed — no guilt",                      type:"break"   },
    { time:"1:00 PM",  label:"Lunch",                                         type:"break"   },
    { time:"2:00 PM",  label:"📤 GitHub: 1 small commit",                      type:"habit"   },
    { time:"3:00 PM",  label:"LinkedIn: 1 post OR 3 comments",                type:"habit"   },
    { time:"4:00 PM",  label:"Walk outside — medicine today",                 type:"health"  },
    { time:"5:00 PM",  label:"Rest / dinner prep",                            type:"break"   },
    { time:"7:00 PM",  label:"Light tutorial if energy allows",               type:"review"  },
    { time:"9:00 PM",  label:"Plan tomorrow",                                 type:"plan"    },
    { time:"10:00 PM", label:"Wind down",                                     type:"wind"    },
    { time:"11:00 PM", label:"😴 Sleep — extra important today",              type:"sleep"   },
  ],
  gap: [
    { time:"Travel",      label:"Podcast/YouTube on skill topic",             type:"review"  },
    { time:"Free hour",   label:"1 concept note on phone",                    type:"work"    },
    { time:"Anytime",     label:"LinkedIn: engage 3 posts",                   type:"habit"   },
    { time:"Evening",     label:"📤 GitHub: push notes or 1 tiny commit",      type:"habit"   },
    { time:"Before sleep",label:"Set tomorrow's day type here",               type:"plan"    },
    { time:"11:00 PM",    label:"😴 Sleep — no guilt",                        type:"sleep"   },
  ],
  interview: [
    { time:"5:00 AM",       label:"Normal wake — light breakfast",            type:"ritual"  },
    { time:"6:00 AM",       label:"20 min exercise — calms nerves",           type:"health"  },
    { time:"7:00 AM",       label:"Review KEY concepts only — no new things", type:"review"  },
    { time:"9:00 AM",       label:"Practice 5 behavioral questions (STAR)",   type:"work"    },
    { time:"10:00 AM",      label:"Rest — calm nervous system",               type:"break"   },
    { time:"Pre-interview", label:"5-min breathing — you are prepared",       type:"ritual"  },
    { time:"🎯 INTERVIEW",  label:"Execute — listen, think aloud, clarify",   type:"work"    },
    { time:"Post-interview",label:"📝 30-min debrief: asked/wins/improve",    type:"plan"    },
    { time:"Evening",       label:"REST — you showed up",                     type:"break"   },
    { time:"Before sleep",  label:"📤 GitHub push + plan tomorrow",            type:"habit"   },
    { time:"11:00 PM",      label:"😴 Sleep — recovery IS preparation",       type:"sleep"   },
  ],
  rest: [
    { time:"No schedule", label:"No pressure — rest IS part of the process",  type:"ritual"  },
    { time:"Anytime",     label:"✅ GitHub: 1 commit (even smallest)",         type:"habit"   },
    { time:"Anytime",     label:"✅ LinkedIn: 1 comment",                      type:"habit"   },
    { time:"Anytime",     label:"✅ Plan tomorrow (5 min only)",               type:"plan"    },
    { time:"By 11 PM",    label:"😴 8 hrs sleep — brain consolidates here",   type:"sleep"   },
  ],
};

export const DEFAULT_DAY_SCHEDULES = {
  Mon: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"10:00 AM", label:"Breakfast + Rest",                                     type:"break"      },
    { time:"11:00 AM", label:"🔥 PRIMARY LEARNING — Session + Practice + Q&A Notes", type:"work"       },
    { time:"1:30 PM",  label:"STAR Recording (record answers)",                      type:"review"     },
    { time:"3:00 PM",  label:"Secondary Skill study",                                type:"work"       },
    { time:"4:30 PM",  label:"Go Out (walk / fresh air)",                            type:"health"     },
    { time:"5:30 PM",  label:"Family / Friends / Personal",                          type:"relaxation" },
    { time:"7:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Tue: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Pramod Demo Session",                                  type:"work"       },
    { time:"9:30 AM",  label:"Temple",                                               type:"ritual"     },
    { time:"11:00 AM", label:"Breakfast",                                            type:"break"      },
    { time:"12:00 PM", label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"2:00 PM",  label:"Quick Learning (tutorial / concept)",                  type:"review"     },
    { time:"4:00 PM",  label:"Go Out",                                               type:"health"     },
    { time:"6:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Wed: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"10:00 AM", label:"Breakfast + Rest",                                     type:"break"      },
    { time:"11:00 AM", label:"🔥 PRIMARY LEARNING — Session + Practice + Q&A Notes", type:"work"       },
    { time:"1:30 PM",  label:"STAR Recording (record answers)",                      type:"review"     },
    { time:"3:00 PM",  label:"Secondary Skill study",                                type:"work"       },
    { time:"4:30 PM",  label:"Go Out",                                               type:"health"     },
    { time:"5:30 PM",  label:"Family / Friends / Personal",                          type:"relaxation" },
    { time:"7:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Thu: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Pramod Demo Session",                                  type:"work"       },
    { time:"10:00 AM", label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"12:00 PM", label:"Quick Learning (tutorial / concept)",                  type:"review"     },
    { time:"2:00 PM",  label:"Go Out",                                               type:"health"     },
    { time:"4:00 PM",  label:"Family / Friends / Personal",                          type:"relaxation" },
    { time:"6:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Fri: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"10:00 AM", label:"Breakfast + Rest",                                     type:"break"      },
    { time:"11:00 AM", label:"🔥 PRIMARY LEARNING — Session + Practice + Q&A Notes", type:"work"       },
    { time:"1:30 PM",  label:"STAR Recording (record answers)",                      type:"review"     },
    { time:"3:00 PM",  label:"Secondary Skill study",                                type:"work"       },
    { time:"4:30 PM",  label:"Go Out",                                               type:"health"     },
    { time:"5:30 PM",  label:"Family / Friends / Personal",                          type:"relaxation" },
    { time:"7:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Sat: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Gym & Workout (1 hour)",                               type:"health"     },
    { time:"7:00 AM",  label:"Freshen Up",                                           type:"ritual"     },
    { time:"8:00 AM",  label:"Pramod Demo Session",                                  type:"work"       },
    { time:"9:30 AM",  label:"Temple",                                               type:"ritual"     },
    { time:"11:00 AM", label:"Job Hunting & Apply",                                  type:"work"       },
    { time:"1:00 PM",  label:"3× AI BLUEPRINT SESSION",                              type:"work"       },
    { time:"4:00 PM",  label:"Learning Part (new concept / tutorial)",               type:"review"     },
    { time:"6:00 PM",  label:"Stop & Go Out",                                        type:"health"     },
    { time:"7:00 PM",  label:"Review + Pending Notes",                               type:"review"     },
    { time:"9:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
  Sun: [
    { time:"5:00 AM",  label:"Shower + Shiva Mantra (108 times)",                   type:"ritual"     },
    { time:"6:00 AM",  label:"Rest / Light Walk — No Gym, Recovery Day",             type:"health"     },
    { time:"8:00 AM",  label:"Personal Time",                                        type:"relaxation" },
    { time:"10:00 AM", label:"Job Hunting (Light)",                                  type:"work"       },
    { time:"12:00 PM", label:"3× AI BLUEPRINT SESSION",                              type:"work"       },
    { time:"3:00 PM",  label:"FREE FORM — anything you feel like doing",             type:"relaxation" },
    { time:"7:00 PM",  label:"Dinner → Wind down",                                   type:"wind"       },
    { time:"11:00 PM", label:"😴 Sleep",                                             type:"sleep"      },
  ],
};

export const BANNERS = {
  full:      { cls:'banner-full',      icon:'⚡', text:'Full Day — Maximum productivity. 3 deep work blocks. Execute.' },
  exhausted: { cls:'banner-exhausted', icon:'😮‍💨', text:'Exhausted Day — Lighter load. Passive learning + non-negotiables.' },
  gap:       { cls:'banner-gap',       icon:'✈️',  text:'Gap/Travel Day — Stay connected. Micro-learning + habits only.' },
  interview: { cls:'banner-interview', icon:'🎯', text:'Interview Day — You are ready. Trust your preparation. Execute.' },
  rest:      { cls:'banner-rest',      icon:'🌿', text:'Rest Day — Recovery is progress. Non-negotiables only, then sleep.' },
};

export const SCHED_TITLES = {
  full:'⚡ FULL DAY SCHEDULE — 5AM TO 11PM', 
  exhausted:'😮‍💨 EXHAUSTED DAY SCHEDULE',
  gap:'✈️ GAP/TRAVEL — MICRO TASKS', 
  interview:'🎯 INTERVIEW DAY SCHEDULE', 
  rest:'🌿 REST DAY',
};

export const FOCUS_MAP = {
  full:      { name:'Playwright + TypeScript',  sub:'Tier 1 · Primary · 3 deep work blocks' },
  exhausted: { name:'Playwright (review only)', sub:'Tier 1 · Videos + recap only' },
  gap:       { name:'Mobile Learning',          sub:'Podcast/YouTube on current skill' },
  interview: { name:'Interview Prep Mode',      sub:'Behavioral + key concepts review' },
  rest:      { name:'Non-Negotiables Only',     sub:'GitHub + LinkedIn + Plan tomorrow' },
};

export const SKILLS_DATA = [
  { tier:'tier1', name:'TIER 1 — CRITICAL', color:'#ef4444', skills:[
    { id:'playwright',  name:'Playwright — Beginner to Advanced', note:'AI Blueprint 3x + Playwright Mastery (IN PROGRESS)', def:55 },
    { id:'typescript',  name:'TypeScript for UI Testing',         note:'Core language for modern Playwright frameworks',     def:40 },
  ]},
  { tier:'tier2', name:'TIER 2 — HIGH VALUE', color:'#f97316', skills:[
    { id:'api_playwright', name:'Playwright API Testing',     note:'API-level testing via Playwright',            def:20 },
    { id:'api_postman',    name:'API Testing with Postman',   note:'REST fundamentals + advanced scenarios',      def:35 },
    { id:'api_contract',   name:'API Contract Testing',       note:'Pact framework, schema validation',           def:10 },
    { id:'api_strategy',   name:'API Testing Strategy',       note:'Production-level concepts, backend QA',       def:15 },
  ]},
  { tier:'tier3', name:'TIER 3 — EMPLOYABILITY', color:'#f59e0b', skills:[
    { id:'cicd_github', name:'CI/CD with GitHub Actions', note:'YAML workflows + test pipelines',      def:30 },
    { id:'sql',         name:'SQL — Basics to Mid Level', note:'Queries, joins, backend QA',           def:25 },
    { id:'docker',      name:'Docker for QA Engineers',   note:'Containers, test environments',        def:15 },
    { id:'jenkins',     name:'Jenkins Pipelines',         note:'Classic CI/CD, widely used',           def:10 },
  ]},
  { tier:'tier4', name:'TIER 4 — DIFFERENTIATORS', color:'#6c47ff', skills:[
    { id:'ai_agents',   name:'AI Agents & Sub-agents',              note:'Building + testing AI agents',     def:30 },
    { id:'prompt_eng',  name:'Prompt Engineering',                   note:'Effective LLM prompting',         def:40 },
    { id:'llm_testing', name:'Testing LLMs Properly',                note:'Evaluation, hallucination detect', def:15 },
    { id:'selenium_ai', name:'Selenium → Playwright Migration (AI)', note:'AI-assisted migration',           def:10 },
  ]},
  { tier:'tier5', name:'TIER 5 — EDGE', color:'#22c55e', skills:[
    { id:'claude_code', name:'Claude Code for Automation',     note:'AI-powered frameworks',         def:35 },
    { id:'agile',       name:'Agile/Scrum/SAFe',              note:'Ceremonies, QA in Agile teams', def:45 },
    { id:'github_adv',  name:'GitHub Actions (Advanced)',      note:'Matrix, secrets, complex flows', def:20 },
  ]},
];

export const TIER_COLORS = { 
  tier1:'#ef4444', 
  tier2:'#f97316', 
  tier3:'#f59e0b', 
  tier4:'#6c47ff', 
  tier5:'#22c55e' 
};

export const DEFAULT_NON_NEG = [
  { id:'github',   label:'📤 Push to GitHub (even 1 commit — no matter what)' },
  { id:'linkedin', label:'💼 LinkedIn: 1 post OR 3 meaningful comments' },
  { id:'plan',     label:'🗓️ Plan tomorrow (5 min max)' },
];

export const WEEK_DAYS = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];

export const DEFAULT_WEEK_PLAN = {
  Mon:{ type:'full',      skill:'Playwright + TypeScript (Deep Work)' },
  Tue:{ type:'full',      skill:'API Testing — Playwright + Postman' },
  Wed:{ type:'full',      skill:'TypeScript + CI/CD GitHub Actions' },
  Thu:{ type:'full',      skill:'API Contract Testing + Strategy' },
  Fri:{ type:'full',      skill:'SQL basics + Docker intro' },
  Sat:{ type:'exhausted', skill:'Review week progress + LinkedIn posts' },
  Sun:{ type:'rest',      skill:'Rest + plan next week' },
};

export const NOTE_TYPES = [
  { id:'all',       label:'All',       color:'#5a6080', bg:'#f0f2f8'  },
  { id:'recruiter', label:'📞 Recruiter', color:'#2563eb', bg:'#dbeafe' },
  { id:'interview', label:'🎯 Interview', color:'#dc2626', bg:'#fee2e2' },
  { id:'learning',  label:'📚 Learning',  color:'#5b21b6', bg:'#ede9ff' },
  { id:'idea',      label:'💡 Idea',       color:'#d97706', bg:'#fef3c7' },
  { id:'followup',  label:'⚠️ Follow-up',  color:'#c2410c', bg:'#ffedd5' },
  { id:'interrupt', label:'⚡ Interrupt',  color:'#be185d', bg:'#fce7f3' },
  { id:'general',   label:'📝 General',    color:'#475569', bg:'#f1f5f9' },
];

export const HUNT_DAY_CFG = {
  0: { mode: 'OUTREACH MODE', cls: 'hunt-out', icon: '🌐', desc: 'LinkedIn posts, recruiter connects, profile polish.' },
  1: { mode: 'SELECTIVE APPLY', cls: 'hunt-mon', icon: '🎯', desc: 'Apply 80%+ matches only. Clear ALL follow-ups first.' },
  2: { mode: 'APPLY HARD', cls: 'hunt-hard', icon: '🚀', desc: 'Every 75%+ listing. Active follow-ups mandatory.' },
  3: { mode: 'APPLY HARD', cls: 'hunt-hard', icon: '🚀', desc: 'Apply + follow up all active conversations.' },
  4: { mode: 'APPLY HARD', cls: 'hunt-hard', icon: '🚀', desc: 'Final push. Close every open loop.' },
  5: { mode: 'OUTREACH MODE', cls: 'hunt-out', icon: '🤝', desc: 'LinkedIn FUs, recruiter connects, profile activity.' },
  6: { mode: 'BUILD & CONNECT', cls: 'hunt-out', icon: '📝', desc: 'Posts, profile updates, recruiter network building.' }
};

export const HUNT_STATUS_MAP = {
  applied: { label: 'Applied', cls: 'hs-applied' },
  screening: { label: 'Awaiting Reply', cls: 'hs-screening' },
  interview: { label: 'Interview', cls: 'hs-interview' },
  consideration: { label: 'In Consideration', cls: 'hs-consider' },
  close: { label: 'Near Close', cls: 'hs-close' },
  rejected: { label: 'Rejected', cls: 'hs-rejected' },
  stale: { label: 'Stale', cls: 'hs-stale' },
  closed: { label: 'Closed', cls: 'hs-closed' }
};

export const HUNT_GROUPS = [
  { key: 'hot', label: 'HOT — Interviews & Active', cls: 'hg-hot', statuses: ['interview', 'consideration', 'close', 'screening'] },
  { key: 'applied', label: 'APPLIED / PENDING', cls: 'hg-applied', statuses: ['applied'] },
  { key: 'stale', label: 'STALE — Consider Closing', cls: 'hg-stale', statuses: ['stale'] },
  { key: 'closed', label: 'CLOSED / REJECTED', cls: 'hg-closed', statuses: ['rejected', 'closed'] }
];

export const HUNT_SEED = [
  { "id": "nutanix-automation-blr-20260525", "company": "Nutanix (Diversity Nexus)", "role": "Automation Engineer", "location": "Bangalore - Hybrid", "appliedDate": "2026-05-25", "status": "applied", "followupDate": "2026-06-01", "contact": "Sumanth", "channel": "Email / Recruiter", "source": "", "match": "", "notes": "Via recruiter Sumanth (Telugu, Diversity Nexus). Updated resume with K8s + Network Automation + LLMs. 30% hike mentioned" }, 
  { "id": "certa-sdet-wf-20260504", "company": "Certa", "role": "SDET (Software Dev Engineer in Test)", "location": "Remote - India", "appliedDate": "2026-05-04", "status": "screening", "followupDate": "2026-05-04", "contact": "Vibha M", "channel": "Wellfound / Email", "source": "", "match": "", "notes": "CODERBYTE TEST — complete if not done! Applied Wellfound. SDET II. 20-25L Remote. TypeScript+Playwright+AWS. Recruiter: " }, 
  { "id": "ust-tester3-ref-20260504", "company": "UST (Tester III)", "role": "Tester III", "location": "", "appliedDate": "2026-05-04", "status": "consideration", "followupDate": "2026-05-11", "contact": "Cousin referral", "channel": "Internal referral", "source": "", "match": "", "notes": "Auto-considered. Cousin referral. UST global IT services. Check with cousin for HR contact + next steps" }, 
  { "id": "resillion-qa-20260428", "company": "Resillion", "role": "QA / Test Automation", "location": "", "appliedDate": "2026-04-28", "status": "screening", "followupDate": "2026-05-01", "contact": "Dhinesh Raj", "channel": "LinkedIn", "source": "", "match": "", "notes": "LinkedIn recruiter connect. Resume sent Apr 28. 15-min call pending" }, 
  { "id": "scriptassistuk-qa-20260317", "company": "Script Assist UK", "role": "QA Automation Playwright TS", "location": "Remote", "appliedDate": "2026-03-17", "status": "interview", "followupDate": "2026-05-01", "contact": "Ben Hamburger (CEO)", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "CEO (Ben) interview Apr 17. FU sent Apr 27. No response yet. Final check" }, 
  { "id": "aeonis-qa-20260418", "company": "Aeonis Technology", "role": "QA Automation Engineer", "location": "Bengaluru", "appliedDate": "2026-04-18", "status": "screening", "followupDate": "2026-04-30", "contact": "Megha", "channel": "LinkedIn / Email", "source": "", "match": "", "notes": "AI screening Apr 18. FU sent Apr 27. Waiting for Megha's response" }, 
  { "id": "capgemini-qa-20260322", "company": "Capgemini", "role": "Playwright Automation", "location": "Bengaluru", "appliedDate": "2026-03-22", "status": "interview", "followupDate": "2026-04-21", "contact": "Prajakta B. Rajput", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "Interview Apr 14. Thank you sent Apr 18. Follow up Prajakta NOW - 41d overdue!!!" }, 
  { "id": "infineon-qa-20260322", "company": "Infineon Technologies", "role": "QA Automation", "location": "Bengaluru", "appliedDate": "2026-03-22", "status": "close", "followupDate": "2026-04-23", "contact": "Anand N. Rawal", "channel": "LinkedIn", "source": "", "match": "", "notes": "Interview Apr 7. Final FU Apr 18. Close deadline PASSED (39d overdue) - send final close msg NOW" }, 
  { "id": "deloitte-dec-qa-blr-20260525", "company": "Deloitte (DEC)", "role": "Sr. Executive - Test Automation", "location": "Bangalore - Hybrid", "appliedDate": "2026-05-25", "status": "applied", "followupDate": "2026-06-01", "contact": "Rakshitha SM", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "Applied May 25 via LinkedIn. Digital Excellence Centre team. 2-4yr automation. Hybrid BLR. Follow-up DM sent to Rakshith" }, 
  { "id": "hackerrank-sdet-i-blr-20260525", "company": "HackerRank", "role": "SDET I", "location": "Bengaluru - Hybrid (Mon/Wed/Thu)", "appliedDate": "2026-05-25", "status": "screening", "followupDate": "2026-05-27", "contact": "HackerRank Hiring Team", "channel": "Email (Chakra AI)", "source": "", "match": "", "notes": "🔥 AI VOICE INTERVIEW RECEIVED May 25 8:48PM (Chakra AI, take-home). Apply May 25 → Interview same day! Complete Chakra i" }, 
  { "id": "experian-sdet-hyd-20260525", "company": "Experian", "role": "SDET (Software Dev Engineer in Test)", "location": "Hyderabad - Onsite", "appliedDate": "2026-05-25", "status": "applied", "followupDate": "2026-06-01", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 25 via Indeed. 88% match. Playwright+CI/CD+API Testing+Agentic AI (GitHub Copilot/Claude/Cursor)+Fintech. De" }, 
  { "id": "ibm-qa-auto-20260512", "company": "IBM", "role": "Quality Engineer - Automation", "location": "India", "appliedDate": "2026-05-12", "status": "screening", "followupDate": "2026-05-26", "contact": "", "channel": "IBM Careers", "source": "", "match": "", "notes": "Coding assessment DONE May 14 (~37 min). Waiting for next step — video interview or English assessment email. Monitor in" }, 
  { "id": "groww-set2-blr-20260512", "company": "Groww", "role": "Software Engineer in Test II", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 12. Major fintech/wealthtech unicorn. SEIT II = strong brand name." }, 
  { "id": "piramal-sdet2-blr-20260512", "company": "Piramal Finance", "role": "SDET2", "location": "Bengaluru", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 12. Fintech/NBFC domain — strong payments domain fit!" }, 
  { "id": "bottomline-qa2-blr-20260512", "company": "Bottomline Technologies", "role": "QA Automation Engineer", "location": "Bengaluru - Hybrid", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 12. Major fintech payments product company ($1B+). Hybrid BLR. Monitor inbox." }, 
  { "id": "trellix-sdet-naukri-20260511", "company": "Trellix", "role": "SDET Automation Test Engineer", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "Naukri", "source": "", "match": "", "notes": "Applied May 12 via Naukri. Playwright+Python+API+Docker. 2-4yr exact fit. Cybersecurity product co." }, 
  { "id": "firstadvantage-qa-blr-20260512", "company": "First Advantage", "role": "Associate Software QA Engineer", "location": "Bengaluru", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn / Company", "source": "", "match": "", "notes": "Applied May 12. Background verification SaaS. Associate level = good fit for 2yr exp." }, 
  { "id": "aisquared-qa-blr-20260512", "company": "AISquared", "role": "QA Engineer", "location": "Bengaluru - Remote", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-06-01", "contact": "", "channel": "LinkedIn / Indeed", "source": "", "match": "", "notes": "Applied May 12 via LinkedIn + re-applied via Indeed May 25. AI product company — testing AI workflows. 78% match. Remote" }, 
  { "id": "shakpe-qa-blr-20260512", "company": "ShakePe", "role": "Software Testing Engineer", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 12. Fintech payments startup." }, 
  { "id": "callquest-qa-blr-20260512", "company": "Call Quest Solution", "role": "QA Automation Engineer", "location": "Bengaluru", "appliedDate": "2026-05-12", "status": "applied", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 12." }, 
  { "id": "itron-qa-blr-20260512", "company": "Itron, Inc.", "role": "Software QA Engineer", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-12", "status": "rejected", "followupDate": "2026-05-19", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "REJECTED May 13 via Workday email. Have not been selected. Closed." }, 
  { "id": "ggwp-qa-20260504", "company": "GGWP", "role": "QA Engineer", "location": "Remote - India", "appliedDate": "2026-05-04", "status": "applied", "followupDate": "2026-05-11", "contact": "Ankita Bhansali", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "Applied May 4 via Wellfound. Gaming startup (SF). Remote India. 15-21L. DM Ankita Bhansali on LinkedIn!" }, 
  { "id": "headout-set-li-20260504", "company": "Headout", "role": "Software Engineer in Test", "location": "Bengaluru", "appliedDate": "2026-05-04", "status": "rejected", "followupDate": "2026-05-13", "contact": "", "channel": "", "source": "", "match": "", "notes": "REJECTED May 13 by Kajal (life@headout.com). High volume, not moving forward. Can reapply after 1 year. Closed." }, 
  { "id": "ust-tester2-ref-20260504", "company": "UST (Tester II)", "role": "Tester II", "location": "", "appliedDate": "2026-05-04", "status": "applied", "followupDate": "2026-05-11", "contact": "Cousin referral", "channel": "Internal referral", "source": "", "match": "", "notes": "Applied May 4. Cousin referral. UST global IT services. Referral track - monitor inbox for HR contact" }, 
  { "id": "recruewai-automation-20260502", "company": "Recrew AI", "role": "Automation Engineer", "location": "Bengaluru - Hybrid", "appliedDate": "2026-05-02", "status": "applied", "followupDate": "2026-05-09", "contact": "", "channel": "Monitor inbox", "source": "", "match": "", "notes": "Applied May 2 via LinkedIn. AI recruitment platform. Monitor inbox" }, 
  { "id": "hired-qa-remote-20260502", "company": "Hired", "role": "Software QA Engineer", "location": "India - Remote", "appliedDate": "2026-05-02", "status": "applied", "followupDate": "2026-05-09", "contact": "", "channel": "Monitor inbox", "source": "", "match": "", "notes": "Applied May 2 via LinkedIn. Remote full-time. Monitor inbox" }, 
  { "id": "clario-qa-20260428", "company": "Clario (Thermo Fisher)", "role": "QA Engineer", "location": "Remote", "appliedDate": "2026-04-28", "status": "pending", "followupDate": "2026-05-01", "contact": "", "channel": "Naukri/Company site", "source": "", "match": "", "notes": "78% match. 12.7-14L. Selenium+API+CI/CD. 1-3yr. APPLY on company site if not yet done" }, 
  { "id": "gaea-qa-20260428", "company": "Gaea Technologies", "role": "QA Automation Engineer", "location": "Bengaluru", "appliedDate": "2026-04-28", "status": "applied", "followupDate": "2026-04-30", "contact": "", "channel": "Naukri", "source": "", "match": "", "notes": "Naukri. Playwright+Python+API Testing. 1-2yr. Applied Apr 28" }, 
  { "id": "drinkprime-qa-20260428", "company": "DrinkPrime", "role": "Junior QA Engineer (Automation)", "location": "Bengaluru", "appliedDate": "2026-04-28", "status": "screening", "followupDate": "2026-04-30", "contact": "", "channel": "Naukri", "source": "", "match": "", "notes": "Naukri. Playwright explicit req. 0-2yr. In Consideration by recruiter" }, 
  { "id": "gsstech-sdet-20260428", "company": "GSSTech Group", "role": "Playwright Automation Engineer (SDET)", "location": "Bengaluru", "appliedDate": "2026-04-28", "status": "applied", "followupDate": "2026-04-30", "contact": "", "channel": "Naukri/LinkedIn", "source": "", "match": "", "notes": "LinkedIn/Naukri. Playwright SDET. Applied Apr 28" }, 
  { "id": "mantras2success-qa-20260428", "company": "Mantras2Success", "role": "QA Automation Engineer", "location": "Bengaluru", "appliedDate": "2026-04-28", "status": "applied", "followupDate": "2026-04-30", "contact": "", "channel": "Naukri", "source": "", "match": "", "notes": "Naukri. Playwright/Cypress/Selenium. 1-2yr. Consulting firm" }, 
  { "id": "decentro-sdet-20260427", "company": "Decentro", "role": "SDET", "location": "Bengaluru - Hybrid", "appliedDate": "2026-04-27", "status": "applied", "followupDate": "2026-04-30", "contact": "Seep Miglani", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "12L-25L. Wellfound. Payment infra - strong fintech domain fit" }, 
  { "id": "logicmonitor-sdet-20260427", "company": "LogicMonitor", "role": "QA/SDET - GenAI Platform", "location": "Bengaluru/Pune - Hybrid", "appliedDate": "2026-04-27", "status": "applied", "followupDate": "2026-04-30", "contact": "Lisa Bengiovanni", "channel": "LinkedIn DM", "source": "", "match": "", "notes": "Wellfound. GenAI platform. Cite AI agents GitHub repo as differentiator" }, 
  { "id": "superliving-qa-20260427", "company": "SuperLiving", "role": "QA Engineer - SDET", "location": "HSR Layout - Onsite", "appliedDate": "2026-04-27", "status": "applied", "followupDate": "2026-05-02", "contact": "", "channel": "Monitor inbox", "source": "", "match": "", "notes": "8L-12L. Wellfound. No recruiter contact yet" }, 
  { "id": "blackduck-sdet-20260427", "company": "Black Duck (Synopsys)", "role": "Software Test Engineer", "location": "Bengaluru", "appliedDate": "2026-04-27", "status": "applied", "followupDate": "2026-05-02", "contact": "", "channel": "Monitor inbox", "source": "", "match": "", "notes": "Greenhouse ATS. Auto-ack expected" }, 
  { "id": "joveoai-sdet-20260427", "company": "Joveo AI", "role": "SDET", "location": "Remote", "appliedDate": "2026-04-27", "status": "applied", "followupDate": "2026-05-02", "contact": "", "channel": "Monitor inbox", "source": "", "match": "", "notes": "Direct ATS. Remote - strong profile fit" }, 
  { "id": "dentira-sdet2-blr-20260514", "company": "Dentira Tech", "role": "SDET II", "location": "Bengaluru/Pune", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed. SDET II, 3yr req. Interview slots: May 18/19/21. F2F final confirmed. Travel: 100%." }, 
  { "id": "avasant-sdet-applied-20260514", "company": "Avasant", "role": "SDET", "location": "Bengaluru", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed." }, 
  { "id": "vtest-sdet-applied-20260514", "company": "VTEST Software", "role": "SDET (Playwright)", "location": "Bengaluru", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed/Keka. 3-6yr req stretch. Expected salary: 6L." }, 
  { "id": "evertz-sdet-blr-20260514", "company": "Evertz Microsystems", "role": "SDET (Playwright/Cypress)", "location": "Bengaluru", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed." }, 
  { "id": "u2o3info-sdet-blr-20260514", "company": "U2O3INFO TECH (Zerozila)", "role": "SDET Playwright", "location": "Bengaluru", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed." }, 
  { "id": "ice-qa-hyd-20260514", "company": "Intercontinental Exchange", "role": "QA Automation Engineer", "location": "Hyderabad", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed. Major US fintech (NYSE parent). Salary asked: 7L. Immediate start." }, 
  { "id": "syneos-qa-hyd-20260514", "company": "Syneos Health", "role": "QA Tester Playwright/TypeScript", "location": "Hyderabad", "appliedDate": "2026-05-14", "status": "applied", "followupDate": "2026-05-21", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 14 via Indeed." }, 
  { "id": "appliedsystems-sdet-blr-20260508", "company": "Applied Systems India", "role": "SDET", "location": "Bengaluru, Karnataka", "appliedDate": "2026-05-19", "status": "applied", "followupDate": "2026-05-26", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 19 via Indeed. Insurance SaaS product company. Playwright+TypeScript+API+CI/CD." }, 
  { "id": "applause-sdet-playwright-hyd-20260429", "company": "Applause", "role": "SDET (Playwright/AI)", "location": "Hyderabad, Telangana", "appliedDate": "2026-05-19", "status": "screening", "followupDate": "2026-05-19", "contact": "Hirebridge ATS", "channel": "Email", "source": "", "match": "", "notes": "COMPLETE HIREBRIDGE FORM — link in email (15:40 May 19), active 30 days (~expires Jun 18). noreply@hirebridgemail.com. A" }, 
  { "id": "codvoai-sdet-remote-20260515", "company": "Codvo.ai", "role": "SDET / QA Engineer", "location": "Remote - India", "appliedDate": "2026-05-19", "status": "closed", "followupDate": "2026-05-19", "contact": "", "channel": "", "source": "", "match": "", "notes": "DECLINED May 19 — Pune onsite + night shift 2:30-11:30PM + package unknown (likely below 6-8L). All 3 dealbreakers. Poli" }, 
  { "id": "rootstock-qa-blr-20260514", "company": "Rootstock Software", "role": "QA Automation Engineer", "location": "Bengaluru, Karnataka", "appliedDate": "2026-05-19", "status": "applied", "followupDate": "2026-05-26", "contact": "", "channel": "Indeed", "source": "", "match": "", "notes": "Applied May 19 via Indeed. Cloud ERP SaaS (Salesforce-native)." }, 
  { "id": "shopflo-sdet-blr-20260513", "company": "Shopflo", "role": "Software Development Engineer in Test", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-19", "status": "applied", "followupDate": "2026-05-26", "contact": "", "channel": "LinkedIn", "source": "", "match": "", "notes": "Applied May 19 via LinkedIn. E-commerce checkout startup. Playwright+TS." }, 
  { "id": "cgi-qa-20260322", "company": "CGI", "role": "QA / Test Engineer", "location": "Bengaluru", "appliedDate": "2026-03-22", "status": "close", "followupDate": "2026-04-23", "contact": "Riji Roselin", "channel": "LinkedIn", "source": "", "match": "", "notes": "Final FU Apr 18. Close deadline Apr 23 PASSED - archive" }, 
  { "id": "datamatics-qa-20260323", "company": "Datamatics", "role": "Playwright Test Automation", "location": "Bengaluru - Hybrid", "appliedDate": "2026-03-23", "status": "stale", "followupDate": "2026-04-01", "contact": "R Praveen Kumar", "channel": "LinkedIn", "source": "", "match": "", "notes": "On hold since Mar. Low priority. Watch only" }, 
  { "id": "browserstack-sdet-20260309", "company": "BrowserStack", "role": "SDET Playwright", "location": "Bengaluru", "appliedDate": "2026-03-09", "status": "stale", "followupDate": "2026-03-14", "contact": "", "channel": "", "source": "", "match": "", "notes": "9 Mar. 70+ days. Consider closing" }, 
  { "id": "lambdatest-qa-20260309", "company": "LambdaTest", "role": "QA Automation", "location": "", "appliedDate": "2026-03-09", "status": "stale", "followupDate": "2026-03-14", "contact": "", "channel": "", "source": "", "match": "", "notes": "9 Mar. 70+ days. Consider closing" }, 
  { "id": "thoughtworks-qa-20260309", "company": "Thoughtworks", "role": "Test Automation Lead", "location": "", "appliedDate": "2026-03-09", "status": "stale", "followupDate": "2026-03-14", "contact": "", "channel": "", "source": "", "match": "", "notes": "9 Mar. 70+ days. Consider closing" }, 
  { "id": "topgrep-qa-20260316", "company": "TopGrep Tech", "role": "Playwright Automation", "location": "", "appliedDate": "2026-03-16", "status": "stale", "followupDate": "2026-03-21", "contact": "", "channel": "", "source": "", "match": "", "notes": "16 Mar. No response" }, 
  { "id": "nable-qa-20260317", "company": "N-able", "role": "Automation Engineer", "location": "", "appliedDate": "2026-03-17", "status": "stale", "followupDate": "2026-03-22", "contact": "", "channel": "", "source": "", "match": "", "notes": "17 Mar. No response" }, 
  { "id": "zluri-sdet-20260317", "company": "Zluri", "role": "SDET", "location": "Bengaluru", "appliedDate": "2026-03-17", "status": "stale", "followupDate": "2026-03-22", "contact": "", "channel": "", "source": "", "match": "", "notes": "17 Mar. No response" }, 
  { "id": "automationtester-qa-20260322", "company": "Automation Tester Co.", "role": "Playwright Automation", "location": "", "appliedDate": "2026-03-22", "status": "stale", "followupDate": "2026-03-27", "contact": "", "channel": "", "source": "", "match": "", "notes": "22 Mar. No response" }, 
  { "id": "replicon-qa-20260322", "company": "Replicon (Deltek)", "role": "Principal Software Engineer", "location": "", "appliedDate": "2026-03-22", "status": "stale", "followupDate": "2026-03-27", "contact": "", "channel": "", "source": "", "match": "", "notes": "22 Mar. No response" }, 
  { "id": "moengage-qa-20260322", "company": "MoEngage", "role": "QA Automation Engineer", "location": "Bengaluru", "appliedDate": "2026-03-22", "status": "stale", "followupDate": "2026-03-27", "contact": "", "channel": "", "source": "", "match": "", "notes": "22 Mar. No response" }, 
  { "id": "relevancelab-qa-20260322", "company": "Relevance Lab", "role": "Test Automation Lead", "location": "", "appliedDate": "2026-03-22", "status": "stale", "followupDate": "2026-03-27", "contact": "", "channel": "", "source": "", "match": "", "notes": "22 Mar. No response" }, 
  { "id": "intactgreen-qa-20260324", "company": "Intact Green Services", "role": "Playwright TS SDET", "location": "", "appliedDate": "2026-03-24", "status": "stale", "followupDate": "2026-03-29", "contact": "", "channel": "", "source": "", "match": "", "notes": "24 Mar. No response" }, 
  { "id": "marketnode-te-20260427", "company": "Marketnode", "role": "Test Engineer", "location": "Bangalore Urban - Hybrid", "appliedDate": "2026-04-27", "status": "rejected", "followupDate": "2026-04-27", "contact": "", "channel": "", "source": "", "match": "", "notes": "Rejected email received Apr 27. Closed" }, 
  { "id": "qualitest-ft-20260428", "company": "Qualitest", "role": "Functional Tester (Insurance)", "location": "Bengaluru", "appliedDate": "2026-04-28", "status": "rejected", "followupDate": "2026-04-28", "contact": "", "channel": "", "source": "", "match": "", "notes": "SKIPPED - 30% match. Manual only, insurance domain, salary 3.5-4.8L" }, 
  { "id": "enparadigm-qa-20260317", "company": "enParadigm", "role": "QA Engineer", "location": "Bengaluru", "appliedDate": "2026-03-17", "status": "rejected", "followupDate": "2026-03-20", "contact": "", "channel": "", "source": "", "match": "", "notes": "Rejected. Closed" }, 
  { "id": "hackerrank-sdet-20260318", "company": "HackerRank", "role": "SDET I", "location": "", "appliedDate": "2026-03-18", "status": "rejected", "followupDate": "2026-03-21", "contact": "", "channel": "", "source": "", "match": "", "notes": "Rejected. Closed" }, 
  { "id": "insightglobal-sdet-20260318", "company": "Insight Global", "role": "SDET Remote", "location": "Remote", "appliedDate": "2026-03-18", "status": "rejected", "followupDate": "2026-03-21", "contact": "", "channel": "", "source": "", "match": "", "notes": "Rejected. Closed" }, 
  { "id": "sasken-qa-20260324", "company": "Sasken Technologies", "role": "Python Automation E1", "location": "Bengaluru", "appliedDate": "2026-03-24", "status": "rejected", "followupDate": "2026-03-27", "contact": "Paul", "channel": "", "source": "", "match": "", "notes": "Rejected by Paul. Closed" }, 
  { "id": "vegaintelli-qa-20260315", "company": "Vega Intellisoft", "role": "QA Automation (Walk-in)", "location": "Bengaluru", "appliedDate": "2026-03-15", "status": "closed", "followupDate": "2026-03-20", "contact": "Jamuna R", "channel": "", "source": "", "match": "", "notes": "No slot confirmed. No response from Jamuna. Closed" }, 
  { "id": "indiacharts-set-20260429", "company": "Indiacharts", "role": "Software Engineer in Test", "location": "Bengaluru", "appliedDate": "2026-04-29", "status": "closed", "followupDate": "2026-04-29", "contact": "", "channel": "", "source": "", "match": "", "notes": "EXPIRED — job listing no longer found on LinkedIn. Dropped from queue May 12." }, 
  { "id": "powerschool-qa1-blr-20260514", "company": "PowerSchool", "role": "Associate Quality Assurance Engineer 1", "location": "Bengaluru", "appliedDate": "2026-05-19", "status": "closed", "followupDate": "2026-05-19", "contact": "", "channel": "", "source": "", "match": "", "notes": "EXPIRED — No longer accepting applications (confirmed May 19 on LinkedIn). Dropped." }, 
  { "id": "assent-sdt-pune-20260503", "company": "Assent", "role": "Software Developer in Test", "location": "Pune - Onsite", "appliedDate": "2026-05-19", "status": "closed", "followupDate": "2026-05-19", "contact": "", "channel": "", "source": "", "match": "", "notes": "SKIPPED — Confirmed Pune onsite (not preferred). Location filter fail." }, 
  { "id": "smartbear-jqa-20260430", "company": "SmartBear", "role": "Junior QA Engineer - Automation", "location": "Pune - Onsite", "appliedDate": "2026-05-19", "status": "closed", "followupDate": "2026-05-19", "contact": "", "channel": "", "source": "", "match": "", "notes": "SKIPPED — Pune onsite (not preferred). Location filter fail." }, 
  { "id": "wework-sdet1-20260429", "company": "WeWork India", "role": "SDET1", "location": "Bengaluru - Onsite", "appliedDate": "2026-05-19", "status": "closed", "followupDate": "2026-05-19", "contact": "", "channel": "", "source": "", "match": "", "notes": "EXPIRED — LinkedIn redirected to different job (Dassault). Listing taken down. Confirmed May 19." }, 
  { "id": "bread-financial-pae-sdet-blr-20260601", "company": "Bread Financial", "role": "Platform Automation Engineer (SDET)", "location": "Bengaluru, Karnataka", "appliedDate": "2026-06-01", "status": "applied", "followupDate": "", "contact": "", "channel": "Indeed", "source": "Indeed", "match": "80", "notes": "Applied Jun 1. Major US fintech (credit/BNPL) BLR office. Playwright+TypeScript+API+CI/CD expected." }, 
  { "id": "clueso-founding-sdet-blr-20260601", "company": "Clueso (YC W23)", "role": "Founding SDET", "location": "Bengaluru, Karnataka", "appliedDate": "2026-06-01", "status": "applied", "followupDate": "", "contact": "", "channel": "Indeed", "source": "Indeed", "match": "80", "notes": "Applied Jun 1. YC W23 AI product startup. First SDET hire. SOC2+ISO certified. Playwright+TS." }, 
  { "id": "netomi-sdet1-remote-20260601", "company": "NETomi", "role": "SDET - I", "location": "Remote - India", "appliedDate": "2026-06-01", "status": "applied", "followupDate": "", "contact": "", "channel": "Indeed", "source": "Indeed", "match": "80", "notes": "Applied Jun 1. Agentic AI CX platform (Delta, MetLife, MGM). SDET-I. Remote India." }
];
